// 杉山幸輝
// 276113
// 1-2

class MyName
{
	public static void main(String[] args)
	{
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("             6NN6                      66");
		System.out.println("             MMM6                   66MMMF");
		System.out.println("             MMM6                 6dMMMM6 ");
		System.out.println("             MMM6              6gMMMMM6");
		System.out.println("      6666666MMML666666   66JMMMMMMD6");
		System.out.println("     6MMMMMMMMMMMMMMMMM dMMMMMM66              ");
		System.out.println("      677777MMMMN777776 TMMY6            66");
		System.out.println("           6MMMMMb                    66MMM6");
		System.out.println("           dMMMNMMb                 6dMMMM6");
		System.out.println("          6MMdMM6MMh6            66MMMMM6");
		System.out.println("         6MMFdMM66MMN6       66dMMMMM6         ");
		System.out.println("        6MM6 MMM6 6MMM6 666NMMMMMM6 ");
		System.out.println("       6MMM6 MMM6  666 6MMMMMM66            ");
		System.out.println("      6MMM6  MMM6       766              6MMN6");
		System.out.println("    6dMMM6   MMM6                      6MMMMF");
		System.out.println("    6MM6     MMM6                   66MMMMB6");
		System.out.println("             MMM6                66MMMMM6 ");
		System.out.println("             MMM6             66MMMMM66");
		System.out.println("             MMM6        66JMMMMMM66");
		System.out.println("             MMM6    6gMMMMMMMM96              ");
		System.out.println("             MMM6   6MMMMMY66");
		System.out.println("             666 ");
		System.out.println("         ");
		System.out.println("                                             ");
		System.out.println("                   ");
		System.out.println("                                     ");
		System.out.println("                                               ");
		System.out.println("                                         ");
		System.out.println("                                   ");
		System.out.println("                                             ");
		System.out.println("                              ");
		System.out.println("                                       ");
		System.out.println("                                           ");
		System.out.println("                           ");
		System.out.println("                                               ");
		System.out.println("                       dMMb              ");
		System.out.println("                       MMM6");
		System.out.println("                       MMM6");
		System.out.println("                       MMM6                  ");
		System.out.println("       6NNx            MMM6            6gNm");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMM6            MMM6            6MMM6");
		System.out.println("       dMMM666666666666MMMN666666666666dMMM ");
		System.out.println("       6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMF");
		System.out.println("         66666666666666666666666666666666");
		System.out.println("");
		System.out.println("     ");
		System.out.println("");
		System.out.println("");
		System.out.println("     ");
		System.out.println("         ");
		System.out.println("                                               ");
		System.out.println("                                         ");
		System.out.println("         ");
		System.out.println("                                             ");
		System.out.println("                    ");
		System.out.println("                                         ");
		System.out.println("                                 ");
		System.out.println("                       666                   ");
		System.out.println("                       MMMF");
		System.out.println("                       MMMF                      ");
		System.out.println("        6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMb");
		System.out.println("         T6666666666666MMM6666666666666666");
		System.out.println("                       MMMF                    ");
		System.out.println("       6666666666666666MMMb66666666666666666 ");
		System.out.println("     6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN");
		System.out.println("      6666666664HY66666666666666TU66666666666");
		System.out.println("              6MMM6            6MMM6");
		System.out.println("               6MMM6          6MMMF");
		System.out.println("                6MMF         6MMM6");
		System.out.println("     6JggggggggggggggggggggggMMMNggggggggggg6");
		System.out.println("     6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD");
		System.out.println("                       MMMF");
		System.out.println("                       MMMF");
		System.out.println("        gNNNNNNNNNNNNNNMMMNNNNNNNNNNNNNNNN6");
		System.out.println("        TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM6");
		System.out.println("                       MMMF");
		System.out.println("                       MMMF");
		System.out.println("                       MMMF                    ");
		System.out.println("                       HMMF");
		System.out.println("                                 ");
		System.out.println("                                           ");
		System.out.println("                                       ");
		System.out.println("                                               ");
		System.out.println("                                   ");
		System.out.println("                                           ");
		System.out.println("                                       ");
		System.out.println("              ");
		System.out.println("                                               ");
		System.out.println("                                           ");
		System.out.println("                                       ");
		System.out.println("                                 ");
		System.out.println("                        ");
		System.out.println("           6MN2        66666666666666666666");
		System.out.println("           6MMF      6MMMMMMMMMMMMMMMMMMMMMMR");
		System.out.println("     JMMc  6MMF  6MM6dMMY66666666666666666MMM6");
		System.out.println("     6MMN  6MMF  JMM6dMM6      dMM6       MMM6");
		System.out.println("      JMM6 6MMF 6MM6 dMMjggggggMMMNgggggg6MMM6");
		System.out.println("       MMN 6MMF 6MM6    6HMMMMMMMMMMMMMMM6");
		System.out.println("       dMM66MMF6MMF            dMM6");
		System.out.println("        66 6MMF6T9    66NMMMMMMMMMMMMMMMMNg6");
		System.out.println("    66JJJJJJMMNJJJJJ6 dMM666666MMMY66666UMMN");
		System.out.println("    6MMMMMMMMMMMMMMM6 MMM6     dMM6     6MMN");
		System.out.println("        6MM6  JMM6    MMMa66666MMMa666666MMN");
		System.out.println("        6MMF  JMM6    MMMHHHHHHMMMHHHHHHHMMN");
		System.out.println("        6MMF  JMM6    MMM6     dMM6     6MMN");
		System.out.println("        6MM6  JMM6    MMMa66666dMMa666666MM6");
		System.out.println("        dMM6  JMM6    6HMMMMMMMMMMMMMMMMMMM6");
		System.out.println("        MMM   JMM666g6         dMM6");
		System.out.println("       6MMF   JMMMMMMB666666666dMMa66666666666");
		System.out.println("      6MMM666MMMMM66 MMMMMMMMMMMMMMMMMMMMMMMM6");
		System.out.println("     6MMMD 6MMM66              dMM6");
		System.out.println("    6MMMD                      dMM6");
		System.out.println("    6YY6                       dMM6");
		System.out.println("                                76");
		System.out.println("                                               ");
		System.out.println("                           ");
		System.out.println("");
	}
}
